name: Build and Deploy
on: [push]
# on:
#   push:
#     branches:
#       - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
      steps:
        - name: Checkout 🛎️
          uses: actions/checkout@v2

        - name: Install and Build 🔧 
          run: |
            npm ci
            npm run build

        - name: Deploy 🚀
          run: |
            npm run deploy